### ISSUE TITLE
Too much warnings in compilation

### ISSUE THREAD

**Issue by dcarlus** [RustyVolley/RustyVolleySrc#11]
I have many warnings (19). I think they are very easy to fix.

**Comment by codec-abc** [comment]
Waiting for a PR. Also, you can use [Clippy](https://github.com/rust-lang/rust-clippy) to get even more warnings.

**Comment by dcarlus** [comment]
Incoming! :factory:

**Comment by codec-abc** [comment]
Thanks. I really appreciate the PR. I left some comments, tell me what you think (and if you want to update it ) before I merge it.

**Comment by codec-abc** [comment]
Also did you use Clippy? I want to use it to see what it says about the code but I didn't find the time yet.

**Comment by dcarlus** [comment]
I have fixed the warnings that appear without Clippy.
With Clippy there are a lot of new recommendations and I do not know how to handle all of them since I do not know the Rust language. I can try to fix some of them... :stuck_out_tongue:

**Comment by dcarlus** [comment]
By the way, are your comments listed in the [Clean code](https://github.com/RustyVolley/RustyVolleySrc/issues/13) issue?

**Comment by codec-abc** [comment]
Some of my comments are listed in the clean code issue but not all of them. Clippy might not be the easiest to get started with Rust. I think if you want to give Rust a try (in the context of this project) the problem listed on the [Clean code issue](https://github.com/RustyVolley/RustyVolleySrc/issues/13) should be fairly trivial once you quickly learn the syntax correct (which is heavily inspired by C++ so it won't be a hard task).
