### ISSUE TITLE
Clean code.

### ISSUE THREAD

**Issue by codec-abc** [RustyVolley/RustyVolleySrc#13]
Thanks to @dcarlus [and his PR](https://github.com/RustyVolley/RustyVolleySrc/pull/12), I realized the code can be cleaned quite a bit.

Among other things, these can done:
- [ ] Remove commented code.
- [ ] Pack tuples with more than 2 fields into a struct.
- [ ] Extract hardcoded const into a separate file (most are already done but there are a few left).
- [ ] Clean git history (merge related commits together and rename them).

**Comment by dcarlus** [comment]
I have removed commented code.
But I am not able to remove most of the hardcoded values as I do not know what they are related to. :sob:

**Comment by codec-abc** [comment]
Nice! The hardcoded values are arbitrary scale value to adapt display. The physic scene is 800x600 and the rendering one is 1920x1080. So there is a 2.4 factor between the 2 scenes. Also assets are often 2 time bigger too. This is why we often end up with [lines like this one](https://github.com/RustyVolley/RustyVolleySrc/blob/master/src/local_game_state.rs#L192). It might be a good idea to rework this part to get less constant. I haven't put much thinking into this for now. Feel free to try some stuff.
