### ISSUE TITLE
Use a true sound library

### ISSUE THREAD

**Issue by dcarlus** [RustyVolley/RustyVolleySrc#14]
I suggest to use a "true" library for playing sound just like [jpernst/alto](https://github.com/jpernst/alto) (OpenAL 1.1) bindings. As a consequence, you can even set the position of the sound in the 3D space! 👍

**Comment by codec-abc** [comment]
Well, for the 3D space it does not make much sense since this is a 2D game. Plus Quicksilver should provide what is needed to what RustyVolley needs as written [in this issue.]

**Comment by codec-abc** [comment]
Also, I would like to avoid depending on a lot of C library. Moreover my primary target is WASM which alto doesn't seem to support right now.

**Comment by dcarlus** [comment]
Right, I thought about the WASM target after having posted the issue...
I think you can wait a long time before it is integrated into Quicksilver. :trollface:

**Comment by codec-abc** [comment]
It will be faster if you help and do a PR for Quicksilver. Also it can be played: if you fade out the music you cant hardcode its length and it will play just nice.

**Comment by dcarlus** [comment]
But a PR implies I know how to code well in Rust, what is not the case. And, to be honest, from what I've seen so far the language does not fit my tastes so I don't fill very implicated in learning Rust lang... 😞

**Comment by codec-abc** [comment]
As you wish. I find a bit strange though that you like C++ very much and Rust isn't your taste while they are very close.

**Comment by codec-abc** [comment]
It is not the syntax. It the fact it isn't safe and the ecosystem is terrible (no package management, bad error message, etc,...).
