### ISSUE TITLE
Development in standby

### ISSUE THREAD

**Issue by dcarlus** [RustyVolley/RustyVolleySrc#15]
You are not developing RustyVolley anymore.
We need a final version with all the *top-notch* features you can add! :+1: :+1: :+1: 
Go, go go, motivation!!!

Otherwise, you won't be able to say anymore again I do never end a project. :wink:

**Comment by codec-abc** [comment]
Didn't you realize yet? It is a trap. I intend you to finish forcing you to learn Rust in the process.

**Comment by dcarlus** [comment]
:astonished: You've cheated me!!
