### ISSUE TITLE
Add proof that the game run at 140 FPS.

### ISSUE THREAD

**Issue by codec-abc** [RustyVolley/RustyVolleySrc#19]
Here you go @dcarlus.

![image](https://user-images.githubusercontent.com/1208646/55168580-5921ff80-5173-11e9-8ca5-4c7df1aadf45.png)

**Comment by codec-abc** [comment]
Look at those beautiful frame times. So neat, so perfect.

**Comment by dcarlus** [comment]
:exclamation: Fake news :exclamation:

**Comment by codec-abc** [comment]
You are fired!!!!
