### ISSUE TITLE
Redo graphics and upgrade resolution.

### ISSUE THREAD

**Issue by codec-abc** [RustyVolley/RustyVolleySrc#4]
@dcarlus is working on it in [the assets repository](https://github.com/RustyVolley/AssetsSources)!

**Comment by codec-abc** [comment]
Also, since you asked @dcarlus, the graphics are kind of responsive,
You can change the [size here](https://github.com/RustyVolley/RustyVolleySrc/blob/master/src/main.rs#L47) and change the [scale factor here](https://github.com/RustyVolley/RustyVolleySrc/blob/master/src/game_constants.rs#L72) and it will just work. If you want to resize the whole stuff at runtime (which can be cool) please feel free to do a pull request :) as you are now a Rust expert.

**Comment by dcarlus** [comment]
:scream: Oh God, me as a Rust expert! Hell, no!!!!

**Comment by dcarlus** [comment]
OK, maybe I will install all RV dependencies... in a virtual machine. I don't want to crap my marvellous Linux installation that works so well and my outstanding Windows configuration with all these things. :trollface: 
But before this, I have many exciting things to do on my own C++ project! ❤️

**Comment by codec-abc** [comment]
Well actually, Rust is really nicely packaged and install its stuff on very specific directory so the chances to mess up with your existing setup is pretty non existent.

Also about your other C++ project you should ![rewrite it in rust](http://i.imgur.com/8acN5PG.png)

**Comment by dcarlus** [comment]
It just was a huge :trollface: for the mess of the system after installing Rust tools! Ah ah!
For rewriting my projects, it is definitely no. But it is off topic... :eyes:
