### ISSUE TITLE
Error on Safari

### ISSUE THREAD

**Issue by nvcken** [RustyVolley/RustyVolleySrc#9]
: ContextError("Could not create WebGL2 context")

**Comment by codec-abc** [comment]
Does it work on other browser on the same computer? If yes, it probably means that Safari doesn't support it which seems confirmed by this [diagram](https://caniuse.com/#feat=webgl2).

**Comment by nvcken** [comment]
yes, Safari doesn't support webGL 2 yet.
is it possible make game fallback to webGL 1 if check webGL 2 doesn't available

**Comment by codec-abc** [comment]
I don't chose directly the WebGL version I use. It is chosen by Quicksilver. If you want WebGL1 support I would suggest doing a PR for Quicksilver to add fallback. But to be honest, WebGL2 doesn't seem like a crazy requirement. Plus I would like to add AntiAliasing at some point which will only be possible with WebGL2. Note, that Safari seems to support WebGL2 and can be enabled from the developer menu.
